description:
  algorithm: ALO
  icon: s3://s3-an2-cism-dev-cism/icons/magna-231208-1557/icon.png
  input_data: s3-an2-cism-dev-cismTest input s3 bucket
  output_data: s3-an2-cism-dev-cismTest input s3 bucket
  overview: AI Advisor Test
  title: magna-231208-1557
  user_parameters: Test params
edgeapp_interface:
  redis_server_uri: ''
edgeconductor_interface:
  inference_result_datatype: image
  support_labeling: true
  train_datatype: table
name: magna-231208-1557
pipeline:
- artifact_uri: s3://s3-an2-cism-dev-cism/ai-solutions/magna-231208-1557/v1/train/artifacts/
  container_uri: 042969618971.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-an2-cism-dev/ai-solutions/magna/magna-231208-1557/train/magna-231208-1557
  dataset_uri:
  - s3://s3-an2-cism-dev-cism/ai-solutions/magna-231208-1557/v1/train/data/
  parameters:
    candidate_parameters:
    - args:
      - concat_dataframes: true
        drop_columns: null
        encoding: null
        groupkey_columns: null
        input_path: train
        time_column: null
        use_all_x: false
        x_columns:
        - Count
        - Converted Torque
        - angle_min
        - angle_mean
        - angle_median
        - angle_std
        - angle_max
        - torque_min
        - torque_mean
        - torque_median
        - torque_std
        - torque_max
        y_column: current_cls
      step: input
    - args:
      - ignore_label_class: NG
        label_sampling: true
        label_sampling_num:
          NG: 1
          OK: 10
        label_sampling_num_type: compare
        negative_target_class: null
        sampling_groupkey_columns: null
        sampling_method: cluster
        sampling_num: null
        sampling_num_type: null
        sampling_type: under
      step: sampling
    - args:
      - data_split_method: cross_validate
        evaluation_metric: accuracy
        model_list:
        - lgb
        - rf
        - cb
        model_type: classification
        num_hpo: 3
        param_range:
          cb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 100
            - 500
          gbm:
            max_depth:
            - 5
            - 7
            n_estimators:
            - 300
            - 500
          lgb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 300
            - 500
          ngb:
            col_sample:
            - 0.6
            - 0.8
            n_estimators:
            - 100
            - 300
          rf:
            max_depth: 6
            n_estimators:
            - 300
            - 500
        shap_ratio: 1.0
      step: train
    selected_user_parameters:
    - args: {}
      step: input
    - args: {}
      step: sampling
    - args: {}
      step: train
    user_parameters:
    - args: []
      step: input
    - args: []
      step: sampling
    - args: []
      step: train
  resource:
    default: standard
  type: train
- artifact_uri: s3://s3-an2-cism-dev-cism/ai-solutions/magna-231208-1557/v1/inference/artifacts/
  container_uri: 042969618971.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-an2-cism-dev/ai-solutions/magna/magna-231208-1557/inference/magna-231208-1557
  dataset_uri:
  - s3://s3-an2-cism-dev-cism/ai-solutions/magna-231208-1557/v1/inference/data/
  model_uri: s3://s3-an2-cism-dev-cism/ai-solutions/magna-231208-1557/v1/train/artifacts/
  parameters:
    candidate_parameters:
    - args:
      - concat_dataframes: true
        drop_columns: null
        encoding: null
        groupkey_columns: null
        input_path: test
        time_column: null
        use_all_x: false
        x_columns:
        - Count
        - Converted Torque
        - angle_min
        - angle_mean
        - angle_median
        - angle_std
        - angle_max
        - torque_min
        - torque_mean
        - torque_median
        - torque_std
        - torque_max
        y_column: null
      step: input
    - args:
      - model_type: classification
        run_shapley: false
      step: inference
    - args: null
      step: output
    selected_user_parameters:
    - args: {}
      step: input
    - args: {}
      step: inference
    - args: {}
      step: output
    user_parameters:
    - args: []
      step: input
    - args: []
      step: inference
    - args: []
      step: output
  resource:
    default: standard
  type: inference
version: 1
wrangler_code_uri: ''
wrangler_dataset_uri: ''
