description:
  algorithm: alo
  icon: s3://icon
  input_data: s3-an2-hyunsoo-dev-aiawithout bucket url
  output_data: s3-an2-hyunsoo-dev-aiawithout bucket url
  overview: testing
  title: solution-woosung-test-3
  user_parameters: params
edgeapp_interface:
  redis_server_uri: ''
edgeconductor_interface:
  inference_result_datatype: image
  support_labeling: true
  train_datatype: table
name: solution-woosung-test-3
pipeline:
- artifact_uri: s3://s3-an2-hyunsoo-dev-aia/artifact/solution-woosung-test-3/train/artifacts/
  container_uri: 086558720570.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-an2-hyunsoo-dev/public/train/solution-woosung-test-3/
  dataset_uri:
  - s3://s3-an2-hyunsoo-dev-aia/ai-solutions/solution-woosung-test-3/v1/train/data/
  parameters:
    candidate_parameters:
    - args:
      - concat_dataframes: true
        drop_columns: null
        encoding: null
        groupkey_columns: null
        input_path: default_train
        time_column: null
        use_all_x: false
        x_columns:
        - input_x0
        - input_x1
        - input_x2
        - input_x3
        y_column: target
      step: input
    - args:
      - custom: {}
        mode: auto
      step: preprocess
    - args:
      - ignore_label_class: null
        label_sampling: false
        label_sampling_num: null
        label_sampling_num_type: null
        negative_target_class: null
        sampling_groupkey_columns: null
        sampling_method: random
        sampling_num: 0.8
        sampling_num_type: ratio
        sampling_type: none
      step: sampling
    - args:
      - data_split_method: cross_validate
        evaluation_metric: accuracy
        model_list:
        - lgb
        - rf
        - cb
        model_type: classification
        num_hpo: 3
        param_range:
          cb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 100
            - 500
          gbm:
            max_depth:
            - 5
            - 7
            n_estimators:
            - 300
            - 500
          lgb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 300
            - 500
          ngb:
            col_sample:
            - 0.6
            - 0.8
            n_estimators:
            - 100
            - 300
          rf:
            max_depth: 6
            n_estimators:
            - 300
            - 500
        shap_ratio: 1.0
      step: train
    selected_user_parameters:
    - args: []
      step: input
    - args: []
      step: preprocess
    - args: []
      step: sampling
    - args: []
      step: train
    user_parameters:
    - args: []
      step: input
    - args: []
      step: preprocess
    - args: []
      step: sampling
    - args: []
      step: train
  resource:
    default: standard
  type: train
- artifact_uri: s3://s3-an2-hyunsoo-dev-aia/artifact/solution-woosung-test-3/inference/artifacts/
  container_uri: 086558720570.dkr.ecr.ap-northeast-2.amazonaws.com/ecr-repo-an2-hyunsoo-dev/public/inference/solution-woosung-test-3/
  dataset_uri:
  - s3://s3-an2-hyunsoo-dev-aia/solution/solution-woosung-test-3/inference/data/
  model_uri: s3://s3-an2-hyunsoo-dev-aia/artifact/solution-woosung-test-3/inference/artifacts/
  parameters:
    candidate_parameters:
    - args:
      - concat_dataframes: true
        drop_columns: null
        encoding: null
        groupkey_columns: null
        input_path: default_inference
        time_column: null
        use_all_x: false
        x_columns:
        - input_x0
        - input_x1
        - input_x2
        - input_x3
        y_column: null
      step: input
    - args:
      - custom: {}
        mode: auto
      step: preprocess
    - args:
      - model_type: classification
        run_shapley: true
      step: inference
    selected_user_parameters:
    - args: []
      step: input
    - args: []
      step: preprocess
    - args: []
      step: inference
    user_parameters:
    - args: []
      step: input
    - args: []
      step: preprocess
    - args: []
      step: inference
  resource:
    default: standard
  type: inference
version: 1
wrangler_code_uri: ''
wrangler_dataset_uri: ''
