description: {}
name: ''
pipeline:
- artifact_uri:
  - s3://s3-an2-hyunsoo-dev-cism/ai-solutions/test_1234/v1/train/data/
  dataset_uri:
  - s3://s3-an2-hyunsoo-dev-cism/ai-solutions/test_1234/v1/train/data/
  type: train
version: 1
