description: {}
name: ''
pipeline:
- parameters:
    candidate_parameters:
    - args:
      - concat_dataframes: true
        drop_columns: null
        encoding: null
        groupkey_columns: null
        input_path: default_train
        time_column: null
        use_all_x: false
        x_columns:
        - input_x0
        - input_x1
        - input_x2
        - input_x3
        y_column: target
      step: input
    - args:
      - custom: {}
        mode: auto
      step: preprocess
    - args:
      - ignore_label_class: null
        label_sampling: false
        label_sampling_num: null
        label_sampling_num_type: null
        negative_target_class: null
        sampling_groupkey_columns: null
        sampling_method: random
        sampling_num: 0.8
        sampling_num_type: ratio
        sampling_type: none
      step: sampling
    - args:
      - data_split_method: cross_validate
        evaluation_metric: accuracy
        model_list:
        - lgb
        - rf
        - cb
        model_type: classification
        num_hpo: 3
        param_range:
          cb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 100
            - 500
          gbm:
            max_depth:
            - 5
            - 7
            n_estimators:
            - 300
            - 500
          lgb:
            max_depth:
            - 5
            - 9
            n_estimators:
            - 300
            - 500
          ngb:
            col_sample:
            - 0.6
            - 0.8
            n_estimators:
            - 100
            - 300
          rf:
            max_depth: 6
            n_estimators:
            - 300
            - 500
        shap_ratio: 1.0
      step: train
    selected_user_parameters:
    - args: {}
      step: input
    - args: {}
      step: preprocess
    - args: {}
      step: sampling
    - args: {}
      step: train
    user_parameters:
    - args:
      - default:
        - true
        description: test1
        name: concat_dataframes
        selectable:
        - true
        - false
        type: single_selection
      - default: []
        description: test2
        name: x_columns
        range:
        - 2
        - 100
        type: string
      step: input
    - args:
      - default:
        - 2
        description: test3
        name: num_hpo
        range:
        - 2
        - 5
        type: int
      step: train
  type: train
version: 1
