## 외부에서 데이터 가져오기 / 결과 저장하는 경우 해당 위치에 지정
external_path:
    - load_train_data:
    - load_inference_data:
    - save_train_artifacts:
    - save_inference_artifacts:
 
## 실험에 필요한 파라미터를 설정함 
## - 해당 위치에서 삭제되면, code 의 default 로 실행
user_parameters:
    - train_workflows:
        - step: input  ## 필수
          parmeters:
            - "A"
            - "B"
            - "C"
            # description :
            # type:
            # allowable_valeus:
            # default:
        - step: output ## 필수
          parameters:
    - inference_workflows:
        - step: input
          parameters:
            description:
            type:
            allowable_values:
            default:
        - step: output             
 
## asset 의 설치 정보를 기록       
asset_source:
    - train_workflows:
        - step: input
          source:  ## git / local 지원
            code: http://mod.lge.com/hub/smartdata/aiplatform/module/data_input.git
            requirements:
              - pandas==3.4 
        - step: output
          source:
            code: http://mod.lge.com/hub/smartdata/aiplatform/module/data_input.git
            requirements:
              - pandas==3.4
    - inference_workflows:
        - step: input
          source:  ## git / local 지원
            code: http://mod.lge.com/hub/smartdata/aiplatform/module/data_input.git
            requirements:
                - pandas==3.4
        - step: output
          source: 
            code: http://mod.lge.com/hub/smartdata/aiplatform/module/data_input.git
            requirements:
                - pandas==3.4
 
control:
    ## 1. 패키지 설치 및 asset 존재 여부를 실험 시마다 체크할지, 한번만 할지 결정
    ## 1-2 requirements.txt 및 종속 패키지들 한번만 설치할 지 매번 설치할지도 결정 
    - check_asset_source: once ## once, every
    ## 2. 생성된 artifacts 를 backup 할지를 결정 True/False
    - backup_artifacts: True
    ## 3. pipeline 로그를 backup 할지를 결정 True/False
    - backup_log: True
    ## 4. 저장 공간 사이즈를 결정 (단위 MB)
    - backup_size: 1000
 
    ## 5. Asset 사이 데이터 전달 방법으로 memory, file 를 지원
    - interface_mode: memory
