### system info. 
'AIC_URI': "https://web.aic-dev.lgebigdata.com/"  ## 실 서버 
"REGION": "ap-northeast-2"
"WORKSPACE_NAME": "cism-ws"  ## magna-ws, cism-ws
"BUILD_METHOD": "buildah"  ## docker, buildah 

'VERSION': 1.1
"LOGIN_MODE": "static" ## ldap, static
"ECR_TAG": "latest"   ## 없어질 사항
"REPOSITORY_TAGS": 
  - "Key=Description,Value=Kubeflow Study"
  - "Key=Owner,Value=DX엔지니어링팀"
  - "Key=IamUser,Value=hyunsoo0802.lim"
  - "Key=ExpriationDate,Value=2024-04"
"AWS_KEY_PROFILE": "register-ai-conductor"
"SUPPORT_TRAINING": True   ## True, False
'REMOTE_BUILD': False
## 'type': 'WINDOWS_CONTAINER'|'LINUX_CONTAINER'|'LINUX_GPU_CONTAINER'|'ARM_CONTAINER'|'WINDOWS_SERVER_2019_CONTAINER'|'LINUX_LAMBDA_CONTAINER'|'ARM_LAMBDA_CONTAINER',
"CODEBUILD_ENV_TYPE": "LINUX_CONTAINER"
## 'computeType': 'BUILD_GENERAL1_SMALL'|'BUILD_GENERAL1_MEDIUM'|'BUILD_GENERAL1_LARGE'|'BUILD_GENERAL1_XLARGE'|'BUILD_GENERAL1_2XLARGE'|'BUILD_LAMBDA_1GB'|'BUILD_LAMBDA_2GB'|'BUILD_LAMBDA_4GB'|'BUILD_LAMBDA_8GB'|'BUILD_LAMBDA_10GB',
"CODEBUILD_ENV_COMPUTE_TYPE": "BUILD_GENERAL1_SMALL"