'AIC_URI': "https://meerkat-ai.com/"
"REGION": "ap-northeast-2"
"WORKSPACE_NAME": "lge-ws" ## 현재 생성되어있는 ws
"BUILD_METHOD": "docker"
'VERSION': 1.0
"LOGIN_MODE": "static" ## ldap 미적용이므로 static
"REPOSITORY_TAGS": [] ## TAG 구분은 정의되지 않았음
"AWS_KEY_PROFILE": "register-solution-storage"
"SUPPORT_TRAINING": False   ## True, False