### system info. 
'AIC_URI': "http://10.158.2.243:9999/"  ## 실 서버 
"REGION": "ap-northeast-2"
"WORKSPACE_NAME": "cism-ws"  ## magna-ws, cism-ws
"BUILD_METHOD": "docker"  ## docker, buildah 

'VERSION': 1.1
"LOGIN_MODE": "static" ## ldap, static
"ECR_TAG": "latest"   ## 없어질 사항
"REPOSITORY_TAGS": 
  - "Key=Description,Value=Kubeflow Study"
  - "Key=Owner,Value=DX엔지니어링팀"
  - "Key=IamUser,Value=hyunsoo0802.lim"
  - "Key=ExpriationDate,Value=2024-04"
"AWS_KEY_PROFILE": "register-ai-conductor"
"SUPPORT_TRAINING": True   ## True, False