### system info. 
'AIC_URI': "https://web.aic-dev.lgebigdata.com/"  ## 실 서버 
"REGION": "ap-northeast-2"
"WORKSPACE_NAME": "cism-ws"  ## magna-ws, cism-ws
"BUILD_METHOD": "docker"  ## docker, buildah 

'VERSION': 1.0
"LOGIN_MODE": "static" ## ldap, static
"ECR_TAG": "latest"   ## 없어질 사항
"REPOSITORY_TAGS": 
  - "Key=Company,Value=LGE"
  - "Key=Owner,Value=IC360"
  - "Key=HQ,Value=CDO"
  - "Key=Division,Value=CDO"
  - "Key=Infra Region,Value=KIC"
  - "Key=Service Mode,Value=OP"
  - "Key=Cost Type,Value=COMPUTING"
  - "Key=Project,Value=CIS"
  - "Key=Sub Project,Value=CISM"
  - "Key=System,Value=AIDX"
"AWS_KEY_FILE": "../aws.key"
"SUPPORT_TRAINING": True   ## True, False